config = {'version': 'v1',
 'config': {'visState': {'filters': [],
   'layers': [{'id': 'd65m18',
     'type': 'heatmap',
     'config': {'dataId': 'Institutions',
      'label': 'Point',
      'color': [221, 178, 124],
      'columns': {'lat': 'Latitude', 'lng': 'Longitude'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'colorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radius': 10},
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'weightField': None, 'weightScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'Institutions': ['Name',
       'Sector',
       'Longitude',
       'Latitude',
       'State']},
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': []},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 39.77933591968462,
   'longitude': -97.56992618843331,
   'pitch': 0,
   'zoom': 3.139508929944764,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'mapStyles': {}}}}